hindi_lesson_plan = [
  {"topic": "Basic Introductions", "goal": "Introducing yourself and basic greetings"},
  {"topic": "Basic Introductions", "goal": "Asking and answering 'What is your name?'"},
  {"topic": "Basic Introductions", "goal": "Saying where you are from and asking others"},
  {"topic": "Basic Introductions", "goal": "Saying your age and asking someone's age"},
  {"topic": "Basic Introductions", "goal": "Saying hello, goodbye, please, and thank you"},
  {"topic": "Basic Introductions", "goal": "Talking about your profession or studies"},
  {"topic": "Basic Introductions", "goal": "Describing your hobbies and interests"},

  {"topic": "Common Phrases", "goal": "Using polite expressions and fillers in conversation"},
  {"topic": "Common Phrases", "goal": "Apologizing and excusing yourself"},
  {"topic": "Common Phrases", "goal": "Understanding and using yes/no and simple agreement phrases"},
  {"topic": "Common Phrases", "goal": "Expressing needs and wants"},
  {"topic": "Common Phrases", "goal": "Using expressions for surprise, happiness, and confusion"},
  {"topic": "Common Phrases", "goal": "Phrases to ask for repetition or clarification"},
  {"topic": "Common Phrases", "goal": "Ending conversations politely"},

  {"topic": "Numbers", "goal": "Saying numbers from 1 to 10"},
  {"topic": "Numbers", "goal": "Saying numbers from 11 to 100"},
  {"topic": "Numbers", "goal": "Using numbers in daily conversation (money, quantity, age)"},
  {"topic": "Numbers", "goal": "Talking about phone numbers and addresses"},
  {"topic": "Numbers", "goal": "Using ordinal numbers (first, second, third, etc.)"},
  {"topic": "Numbers", "goal": "Counting money and change in practical settings"},

  {"topic": "Simple Grammar Concepts", "goal": "Understanding subject-object-verb (SOV) sentence structure"},
  {"topic": "Simple Grammar Concepts", "goal": "Using gender (masculine/feminine) with nouns and adjectives"},
  {"topic": "Simple Grammar Concepts", "goal": "Conjugating simple present tense verbs"},
  {"topic": "Simple Grammar Concepts", "goal": "Forming basic questions and negations"},
  {"topic": "Simple Grammar Concepts", "goal": "Using postpositions correctly"},
  {"topic": "Simple Grammar Concepts", "goal": "Using pronouns appropriately (I, you, he, she, we, they)"},
  {"topic": "Simple Grammar Concepts", "goal": "Using past tense verbs in simple statements"},
  {"topic": "Simple Grammar Concepts", "goal": "Introduction to future tense and intent"},

  {"topic": "Verbs & Actions", "goal": "Using common action verbs (to go, to eat, to do, etc.)"},
  {"topic": "Verbs & Actions", "goal": "Talking about daily routines using present tense"},
  {"topic": "Verbs & Actions", "goal": "Describing what you are doing right now (present continuous)"},
  {"topic": "Verbs & Actions", "goal": "Describing past activities using past tense"},
  {"topic": "Verbs & Actions", "goal": "Expressing future plans and intentions"},
  {"topic": "Verbs & Actions", "goal": "Making polite requests and giving suggestions"},

  {"topic": "Time & Dates", "goal": "Telling time (hours, minutes, AM/PM)"},
  {"topic": "Time & Dates", "goal": "Saying days of the week and months"},
  {"topic": "Time & Dates", "goal": "Talking about the date and your schedule"},
  {"topic": "Time & Dates", "goal": "Describing frequency (always, sometimes, never)"},
  {"topic": "Time & Dates", "goal": "Making appointments or setting meeting times"},
  {"topic": "Time & Dates", "goal": "Talking about special events (birthdays, festivals)"},
  {"topic": "Time & Dates", "goal": "Discussing past or future events with dates"},

  {"topic": "Directions & Places", "goal": "Asking and giving directions"},
  {"topic": "Directions & Places", "goal": "Naming and identifying common places (market, hospital, etc.)"},
  {"topic": "Directions & Places", "goal": "Describing location using prepositions (on, in, next to)"},
  {"topic": "Directions & Places", "goal": "Understanding transportation-related phrases"},
  {"topic": "Directions & Places", "goal": "Talking about city landmarks and famous places"},
  {"topic": "Directions & Places", "goal": "Asking for the nearest ATM, bathroom, or store"},

  {"topic": "Food & Drink", "goal": "Naming common foods and drinks"},
  {"topic": "Food & Drink", "goal": "Ordering food at a restaurant or café"},
  {"topic": "Food & Drink", "goal": "Saying what you like and dislike"},
  {"topic": "Food & Drink", "goal": "Describing meals and ingredients"},
  {"topic": "Food & Drink", "goal": "Describing taste and texture (spicy, sweet, salty, etc.)"},
  {"topic": "Food & Drink", "goal": "Talking about eating habits and preferences"},
  {"topic": "Food & Drink", "goal": "Explaining dietary restrictions or allergies"},

  {"topic": "Shopping & Money", "goal": "Asking how much something costs"},
  {"topic": "Shopping & Money", "goal": "Bargaining or negotiating prices"},
  {"topic": "Shopping & Money", "goal": "Describing products and preferences"},
  {"topic": "Shopping & Money", "goal": "Describing different types of stores"},
  {"topic": "Shopping & Money", "goal": "Asking for specific items while shopping"},
  {"topic": "Shopping & Money", "goal": "Using words for payment methods (cash, card, UPI)"},

  {"topic": "Clothing & Colors", "goal": "Naming common clothing items"},
  {"topic": "Clothing & Colors", "goal": "Describing clothing using colors and sizes"},
  {"topic": "Clothing & Colors", "goal": "Talking about what you are wearing"},
  {"topic": "Clothing & Colors", "goal": "Talking about buying clothes and trying them on"},
  {"topic": "Clothing & Colors", "goal": "Describing traditional Indian clothing"},
  {"topic": "Clothing & Colors", "goal": "Saying what someone else is wearing"},

  {"topic": "Family & Relationships", "goal": "Naming family members"},
  {"topic": "Family & Relationships", "goal": "Talking about your family and their relationships"},
  {"topic": "Family & Relationships", "goal": "Describing people using simple adjectives"},
  {"topic": "Family & Relationships", "goal": "Describing someone’s family structure"},
  {"topic": "Family & Relationships", "goal": "Talking about marital status and relationships"},
  {"topic": "Family & Relationships", "goal": "Using possessive phrases to talk about family"},

  {"topic": "Home & Daily Life", "goal": "Talking about rooms and household items"},
  {"topic": "Home & Daily Life", "goal": "Describing your daily routine at home"},
  {"topic": "Home & Daily Life", "goal": "Talking about chores and activities"},
  {"topic": "Home & Daily Life", "goal": "Explaining your daily or weekly schedule"},
  {"topic": "Home & Daily Life", "goal": "Describing your home or apartment"},
  {"topic": "Home & Daily Life", "goal": "Talking about common household problems (no electricity, etc.)"},

  {"topic": "Emotions & Conditions", "goal": "Expressing how you feel (happy, tired, sick, etc.)"},
  {"topic": "Emotions & Conditions", "goal": "Describing physical and emotional states"},
  {"topic": "Emotions & Conditions", "goal": "Asking others how they are feeling"},
  {"topic": "Emotions & Conditions", "goal": "Talking about stress, relaxation, and mood"},
  {"topic": "Emotions & Conditions", "goal": "Describing symptoms when feeling unwell"},
  {"topic": "Emotions & Conditions", "goal": "Using expressions for hope, worry, or surprise"},

  {"topic": "Weather & Nature", "goal": "Describing the weather today and seasonally"},
  {"topic": "Weather & Nature", "goal": "Talking about natural elements (sun, rain, trees, etc.)"},
  {"topic": "Weather & Nature", "goal": "Using weather vocabulary in small talk"},
  {"topic": "Weather & Nature", "goal": "Talking about seasonal changes"},
  {"topic": "Weather & Nature", "goal": "Describing natural disasters or weather warnings"},
  {"topic": "Weather & Nature", "goal": "Expressing preferences about weather and seasons"},

  {"topic": "Technology & Communication", "goal": "Talking about phones, computers, and common tech terms"},
  {"topic": "Technology & Communication", "goal": "Using phrases for texting, calling, and emailing"},
  {"topic": "Technology & Communication", "goal": "Describing how you use technology daily"},
  {"topic": "Technology & Communication", "goal": "Using Hindi to explain basic app or device problems"},
  {"topic": "Technology & Communication", "goal": "Talking about using social media platforms"},
  {"topic": "Technology & Communication", "goal": "Describing online activities and internet use"},
  {"topic": "Situation: At a Restaurant", "goal": "Reading a menu and asking for recommendations"},
  {"topic": "Situation: At a Restaurant", "goal": "Ordering food and drinks"},
  {"topic": "Situation: At a Restaurant", "goal": "Asking about ingredients or dietary preferences"},
  {"topic": "Situation: At a Restaurant", "goal": "Requesting the bill and making a payment"},

  {"topic": "Situation: At a Market", "goal": "Asking for prices and bargaining"},
  {"topic": "Situation: At a Market", "goal": "Describing what you want to buy (fruits, clothes, etc.)"},
  {"topic": "Situation: At a Market", "goal": "Understanding measurements and quantities"},
  {"topic": "Situation: At a Market", "goal": "Interacting politely with shopkeepers"},

  {"topic": "Situation: Taking Public Transport", "goal": "Asking for directions and nearest bus/train stop"},
  {"topic": "Situation: Taking Public Transport", "goal": "Understanding route numbers and timings"},
  {"topic": "Situation: Taking Public Transport", "goal": "Asking if the bus/train is going to a specific place"},
  {"topic": "Situation: Taking Public Transport", "goal": "Requesting someone to inform you when to get off"},

  {"topic": "Situation: Buying Tickets", "goal": "Asking for ticket prices"},
  {"topic": "Situation: Buying Tickets", "goal": "Asking for round-trip vs. one-way tickets"},
  {"topic": "Situation: Buying Tickets", "goal": "Stating the number of people and destination"},
  {"topic": "Situation: Buying Tickets", "goal": "Understanding the date and time of travel"},

  {"topic": "Situation: At the Doctor's Clinic", "goal": "Explaining your symptoms"},
  {"topic": "Situation: At the Doctor's Clinic", "goal": "Answering basic health-related questions"},
  {"topic": "Situation: At the Doctor's Clinic", "goal": "Understanding medical advice or prescriptions"},
  {"topic": "Situation: At the Doctor's Clinic", "goal": "Describing past health issues or allergies"},

  {"topic": "Situation: At a Hotel", "goal": "Checking in and checking out of a hotel"},
  {"topic": "Situation: At a Hotel", "goal": "Asking about facilities and services"},
  {"topic": "Situation: At a Hotel", "goal": "Requesting room service or assistance"},
  {"topic": "Situation: At a Hotel", "goal": "Reporting issues or complaints politely"},

  {"topic": "Situation: Meeting New People", "goal": "Introducing yourself and making small talk"},
  {"topic": "Situation: Meeting New People", "goal": "Talking about where you're from and why you're visiting"},
  {"topic": "Situation: Meeting New People", "goal": "Asking about someone's work or family"},
  {"topic": "Situation: Meeting New People", "goal": "Keeping a conversation going using questions and responses"},

  {"topic": "Situation: Asking for Help", "goal": "Asking someone to repeat or speak slowly"},
  {"topic": "Situation: Asking for Help", "goal": "Asking for directions or clarification"},
  {"topic": "Situation: Asking for Help", "goal": "Explaining that you're learning Hindi"},
  {"topic": "Situation: Asking for Help", "goal": "Politely requesting assistance in emergencies"},
  {"topic": "Situation: Booking a Tour", "goal": "Inquiring about tour packages and availability"},
  {"topic": "Situation: Booking a Tour", "goal": "Asking about prices, inclusions, and exclusions"},
  {"topic": "Situation: Booking a Tour", "goal": "Understanding tour schedules and pick-up points"},
  {"topic": "Situation: Booking a Tour", "goal": "Confirming a booking or making a reservation"},

  {"topic": "Situation: Visiting a Tourist Attraction", "goal": "Asking for ticket prices and timings"},
  {"topic": "Situation: Visiting a Tourist Attraction", "goal": "Asking for guides or audio tours"},
  {"topic": "Situation: Visiting a Tourist Attraction", "goal": "Learning about historical facts or features"},
  {"topic": "Situation: Visiting a Tourist Attraction", "goal": "Asking for directions within a large site"},

  {"topic": "Situation: Taking a Taxi or Rickshaw", "goal": "Negotiating or confirming the fare"},
  {"topic": "Situation: Taking a Taxi or Rickshaw", "goal": "Giving your destination and checking the route"},
  {"topic": "Situation: Taking a Taxi or Rickshaw", "goal": "Requesting to stop or slow down"},
  {"topic": "Situation: Taking a Taxi or Rickshaw", "goal": "Thanking and paying the driver"},

  {"topic": "Situation: At the Airport", "goal": "Checking in and understanding announcements"},
  {"topic": "Situation: At the Airport", "goal": "Asking about luggage, gates, and timings"},
  {"topic": "Situation: At the Airport", "goal": "Going through customs and immigration"},
  {"topic": "Situation: At the Airport", "goal": "Finding transportation from the airport"},

  {"topic": "Situation: Lost or Looking for Help", "goal": "Saying you're lost and asking for directions"},
  {"topic": "Situation: Lost or Looking for Help", "goal": "Asking someone to call a taxi or guide"},
  {"topic": "Situation: Lost or Looking for Help", "goal": "Describing your location or a nearby landmark"},
  {"topic": "Situation: Lost or Looking for Help", "goal": "Thanking someone for helping you"},

  {"topic": "Situation: At a Temple or Religious Site", "goal": "Understanding customs and etiquette"},
  {"topic": "Situation: At a Temple or Religious Site", "goal": "Asking if photography is allowed"},
  {"topic": "Situation: At a Temple or Religious Site", "goal": "Talking about religious practices respectfully"},
  {"topic": "Situation: At a Temple or Religious Site", "goal": "Participating in or observing rituals"},

  {"topic": "Situation: Exploring Local Culture", "goal": "Asking about local festivals or events"},
  {"topic": "Situation: Exploring Local Culture", "goal": "Discussing art, crafts, and traditions"},
  {"topic": "Situation: Exploring Local Culture", "goal": "Asking about traditional clothing or dances"},
  {"topic": "Situation: Exploring Local Culture", "goal": "Engaging in polite conversation with locals"}
]

